version: '3.8'
services:
  my-postgres:
    image: postgres:13
    container_name: my-postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: QQQqwfyUyF6jxNxskpeKLTsNThYLMNHf
      POSTGRES_DB: test_5zth
    networks:
      - my-network

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp_container
    depends_on:
      - my-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/test_5zth
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: QQQqwfyUyF6jxNxskpeKLTsNThYLMNHf
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
