services:
  - type: web
    name: my-java-app
    env: docker
    plan: free # 根据您的需要可以选择不同的计划
    dockerfilePath: ./Dockerfile
    buildCommand: "" # 留空，因为 Dockerfile 中已经包含构建命令
    startCommand: "" # 留空，因为 Dockerfile 中已经包含启动命令
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: a27382722
    healthCheckPath: /actuator/health
    autoDeploy: true
